### ISSUE TITLE
Not work on http://www.lostfilm.tv/

### ISSUE THREAD

**Issue by heretic13** [antchfx/xquery#1]
When I do

`
package main

import (
    "fmt"
    "log"
    "net/http"

```
"github.com/antchfx/xquery/html"
"golang.org/x/net/html"
```

)

func main() {

```
resp, err := http.Get("http://www.lostfilm.tv/")

if err != nil {
    log.Fatal(err)
}

defer resp.Body.Close()

root, err := html.Parse(resp.Body)
if err != nil {
    log.Fatal(err)
}

var xpath string
xpath = `//title`

node := htmlquery.FindOne(root, xpath)
fmt.Println(htmlquery.InnerText(node))
```

}
`

I get:

panic: unknown HTML node type: 5
goroutine 1 [running]:
panic(0x609180, 0xc042121620)
    C:/Go/src/runtime/panic.go:500 +0x1af
github.com/antchfx/xquery/html.(_htmlNodeNavigator).NodeType(0xc04211d700, 0x0)
    D:/Projects/gopath/src/github.com/antchfx/xquery/html/query.go:120 +0x130
github.com/antchfx/gxpath/internal/build.axisPredicate.func1(0x769000, 0xc04211d700, 0x40f700)
    D:/Projects/gopath/src/github.com/antchfx/gxpath/internal/build/build.go:45 +0x4e
github.com/antchfx/gxpath/internal/query.(_DescendantQuery).Select.func1(0x63cc80, 0xc0421df350)
    D:/Projects/gopath/src/github.com/antchfx/gxpath/internal/query/query.go:236 +0xa9
github.com/antchfx/gxpath/internal/query.(_DescendantQuery).Select(0xc0421df320, 0x763760, 0xc04211d6c0, 0x0, 0xc04211d6c0)
    D:/Projects/gopath/src/github.com/antchfx/gxpath/internal/query/query.go:243 +0x3d
github.com/antchfx/gxpath.(_NodeIterator).MoveNext(0xc04211d6c0, 0xc04211d640)
    D:/Projects/gopath/src/github.com/antchfx/gxpath/select.go:22 +0x50
github.com/antchfx/xquery/html.FindOne(0xc042010150, 0x65de4e, 0x7, 0x0)
    D:/Projects/gopath/src/github.com/antchfx/xquery/html/query.go:33 +0xb4
main.main()
    D:/Projects/gopath/src/Test2/main.go:30 +0x2d8

**Comment by heretic13** [comment]
Node type 5. I think it  - DoctypeNode.
You do not handle it at the moment.

query.go:
func (h *htmlNodeNavigator) NodeType() xpath.NodeType {

**Comment by zhengchun** [comment]
Yes, I forgot a <!Doctype HTML>,handle it as root-node type now. thanks for your feedback.
