### ISSUE TITLE
Not able to install xquery

### ISSUE THREAD

**Issue by sanjay-dc** [antchfx/xquery#10]
go get github.com/antchfx/xquery results in
can't load package: package github.com/antchfx/xquery: no buildable Go source files in /Users/i335366/go/src/github.com/antchfx/xquery, please help.

**Comment by zhengchun** [comment]
Hi,@sanjay-dc, this is a Warning error, tell you no source code file in the xpath directory, you can ignored it, xquery source code already on your computer at /Users/i335366/go/src/github.com/antchfx/xquery, you can check it this path.

**Comment by sanjay-dc** [comment]
Thanks @zhengchun , for the quick response. Your example works fine.

Is there AND OR support in the query ,  I didn't see any examples on that?

**Comment by zhengchun** [comment]
@sanjay-dc , YES, it supported AND OR operation. you can found all feature at [HERE](https://github.com/antchfx/xpath)

https://github.com/antchfx/xpath/blob/master/xpath_test.go#L145

hope you'll like it :smile:
