### ISSUE TITLE
can't return attribute

### ISSUE THREAD

**Issue by herozzm** [antchfx/xquery#11]
```html
<ul>
  <li><p><a href="test.html"></a></p></li>
</ul>
```
expr: ``//ul/li/p/a/@href``
``htmlquery. FindOne`` return a Node, is not attribute, I want to the attribute string, If you use ``htmlquery.SelectAttr``, I also need to split the expression:
```go
split := strings.Split("//ul/li/p/a@href", "@")
node := htmlquery.FindOne(root, split[0])
attribute  := htmlquery.SelectAttr(node, split[1])
```
Too many steps

Can I use an expression in one step? Because the xpath expression can be done, not of using ``htmlquery.SelectAttr``

**Comment by zhengchun** [comment]
Sorry, xquery does not support get attribute value via XPath on now, because [xpath](https://github.com/antchfx/xpath) package does't, i need time to fix it.
