### ISSUE TITLE
匹配错误

### ISSUE THREAD

**Issue by herozzm** [antchfx/xquery#12]
就直接中文吧
```html
<span class="fr date">
    <span style="color:#999;font-size:8px;">
        <script type="text/javascript">
            //something
        </script>
    </span>
&nbsp;&nbsp;2017-05-11
</span>
```

第一个问题：
表达式:``//span[@class='date']``
直接出现panic匹配错误，没有返回err吗？

第二个问题
表达式:``//span[@class]``
返回正常，但是InnerText返回的值还包含了script代码，而不是纯文本？

**Comment by herozzm** [comment]
第二个问题是我搞错了，会过滤script

**Comment by zhengchun** [comment]
`//span[@class='date']` 不会异发panic匹配错误，它会返回`nil`，你需要先判断然后再做处理，比如
```go
if node:=htmlquery.Findone(doc,"//span[@class='date']");node!=nil{
    fmt.Println(htmlquery.OutputHTML(node,true))
}
```
或者你可以考虑`contains`函数，比如：`//span[contains(@class,'date')]`
