### ISSUE TITLE
错误的表达式会触发panic err

### ISSUE THREAD

**Issue by herozzm** [antchfx/xquery#13]
错误的表达式会触发panic err
node := htmlquery.FindOne(root, "span[@class='test')")  //这句
if node == nil {
  //something
}
``span[@class='test')``  应该是 ``span[@class='test']``
能否屏蔽 panic err?

**Comment by zhengchun** [comment]
@herozzm ，错误的表达式会触发panic，需要你修正这个错误的表达式。
你或者可以考虑golang的[recover](https://blog.golang.org/defer-panic-and-recover)

**Comment by zhengchun** [comment]
@herozzm , [XPath](https://github.com/antchfx/xpath)已经支持Compile()方法了。
```go
expr,err:=xpath.Compile("span[@Class='test')")
if err!=nil{
    panic(err)
}
```
