### ISSUE TITLE
Multi-element matching returns false positives

### ISSUE THREAD

**Issue by drauschenbach** [antchfx/xquery#15]
I wrote a unit test to demonstrate that multi-element matching is not working and returns false-positives.

```go
if list := Find(doc, "//book[genre='Fantasy'][author='Corets, Eva']"); len(list) != 1 {
	t.Fatal("//book[genre='Fantasy'][author='Corets, Eva'] items count is not equal 1")
}
```

https://github.com/drauschenbach/xquery/blob/master/xml/query_test.go

**Comment by zhengchun** [comment]
Hi,@drauschenbach ,`//book[genre='Fantasy'][author='Corets, Eva']` matches 2 elements: `<book id="bk103">` and `<book id="bk102">`, not one element.

im not sure whether it is right: `//book[genre='Fantasy'][author='Corets, Eva']` = `//book[genre='Fantasy' or author='Corets, Eva'])` ??

**Comment by drauschenbach** [comment]
Adjacent bracketed elements in a path means AND. At least according to my read of the spec, and this tester site: https://www.freeformatter.com/xpath-tester.html

Or another way to go, that also doesn't work, is this: `//book[genre='Fantasy' and author='Corets, Eva']`

**Comment by zhengchun** [comment]
Update your [XPath](https://github.com/antchfx/xpath) package to solve. 

Thank you for reporting your issue 👍
