### ISSUE TITLE
Attributes nodes probably not handled correctly

### ISSUE THREAD

**Issue by mildred** [antchfx/xquery#16]
Hi,

First, thank you for your work on xpath and xquery for go, I'm adapting your xpath library to another dom structure I have and I looked at the code here to understand how the NodeNavigator worked.

I think I found inconsistencies in your NodeNavigator around attribute nodes, due to the fact that your dom structure don't have first class attribute nodes.

In particular, trying the xpath expression `/a/b/@attr/..` on a document  `<a><b attr="1"/></a>` should select `<b attr="1"/>`. It seems your implementation selects `<a>...</a>` instead.

I think that this is because when you `MoveToParent()` when an attribute is selected moves you to the grandparent of the attribute instead of its parent. It moves to the parent of the element containing the attribute.

When trying to test this kind of xml/query_test.go with

```
	if node := FindOne(doc, "//book/@id/..[1]"); node.SelectAttr("id") != "bk101" {
		t.Fatal("//book/@id/...[1]/@id != bk101")
	}
```

it seems it selects no node, `node` is nil and I get a stack trace

**Comment by zhengchun** [comment]
You are right. i'm fix it. Thanks for your report.
