### ISSUE TITLE
Problem with installation

### ISSUE THREAD

**Issue by ps06756** [antchfx/xquery#18]
Hi, 
When I try to install it on ubuntu 16.04, I am getting the following error: 
`can't load package: package github.com/antchfx/xquery: no buildable Go source files in /home/ps06756/go/src/github.com/antchfx/xquery`, when I run the following command:

` go get github.com/antchfx/xquery`

**Comment by zhengchun** [comment]
see #10 
The source code already downloaded to your disk.
