### ISSUE TITLE
//@href doesn't work

### ISSUE THREAD

**Issue by lexfrei** [antchfx/xquery#2]
Hello!
`//*[@id="whatsnew"]/div/div[2]/strong/a//@href` doesn't work as expected.
My code:
```
package main

import (
	"fmt"
	"net/url"

	"github.com/antchfx/xquery/html"
)

func main() {
	root, err := htmlquery.LoadURL("https://www.apkmirror.com/apk/niantic-inc/pokemon-go")
	if err != nil {
		panic(err)
	}
	urlToAPK := htmlquery.InnerText(htmlquery.FindOne(root, "//*[@id=\"whatsnew\"]/div/div[2]/strong/a//@href"))
	fmt.Println(urlToAPK)
}
```
and i got `Pokémon GO 0.55.0` instead if link.
Is it my fault or your?

**Comment by zhengchun** [comment]
hi,@lexfrei , your xpath expression look correct, it will find and output follow element `<a href="/apk/niantic-inc/pokemon-go/pokemon-go-0-55-0-release/">Pokémon GO 0.55.0</a>`, if you want to get a link,you need a `href` attr value.

```go
elem := htmlquery.FindOne(root, `//*[@id="whatsnew"]/div/div[2]/strong/a/@href`)
for _, attr := range elem.Attr {
	if attr.Key == "href" {
		urlToAPK := attr.Val
		fmt.Println(urlToAPK)
	}
}
```

update1:
the xpath always returns a element object, not a text, even you specified a`@href` in your xpath expression,
so,`htmlquery.InnerText` method returns a find element inner text, not `@href` attr value of this element.

update2:
I added a SelectAttr method https://github.com/antchfx/xquery/commit/98532840638a741af0b180148cab2ae0f71000dc

```go
elem := htmlquery.FindOne(root, `//*[@id="whatsnew"]/div/div[2]/strong/a/@href`)
fmt.Println(htmlquery.SelectAttr(elem,"href"))
```

**Comment by lexfrei** [comment]
Thx for response!
This isn't totally clear for me, but i got it.
Feel free to resolve! <3
