### ISSUE TITLE
Typo in xml leads to error

### ISSUE THREAD

**Issue by marcelloh** [antchfx/xquery#20]
my xml (with a typo in the closing tag of **three**
```
<?xml version="1.0"?>
<Scenarios>
    <scenario>
        <one>1</one>
        <two>2</two>
        <three>3</tree>
    </scenario>
</Scenarios>
```
when I do this:
```
	allScenarios := xmlquery.Find(memXML, "//scenario")
	fmt.Println(len(allScenarios))
```
It doesn't come to to printing of the len, but it raises me an error.
(And I'm not capable of handling it)

**Comment by zhengchun** [comment]
@marcelloh , Its your XML document format error:
`Unable to perform XPath operation. The element type "three" must be terminated by the matching end-tag "</three>".`  

You can try [XPath Tester](https://www.freeformatter.com/xpath-tester.html) to test your XPath expression.

Updated:
If you want to handling query error for invalid XML document, You can try using Golang's `Recover` feature to handle error.

**Comment by marcelloh** [comment]
I know I have this error in the xml. It's handtyped, and every human can make mistakes. However, the error was not thrown by the find option, it's just panics and close down my application.
It would be nicer if find gave me the error too, like this (as example)
```
allScenarios, err := xmlquery.Find(memXML, "//scenario")
if err != nil {
// inform the maker of the xml it has an error
}
fmt.Println(len(allScenarios))
```

Can you give an example in how the recover would work? (I'm a bit unfamiliar with that)
Remember, I want to inform the human it made a typo ;-)

I get this trace btw:
```
panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xc0000005 code=0x0 addr=0x28 pc=0x7689e1]

goroutine 1 [running]:
github.com/antchfx/xquery/xml.(*NodeNavigator).NodeType(0xc042002600, 0x0)
        C:/data/git/GoProjects/src/github.com/antchfx/xquery/xml/query.go:99 +0x31
github.com/antchfx/xpath.axisPredicate.func1(0xa492e0, 0xc042002600, 0x41113f)
        C:/data/git/GoProjects/src/github.com/antchfx/xpath/build.go:44 +0x4e
github.com/antchfx/xpath.(*descendantQuery).Select.func1(0x809c00, 0xc0421ac570)
        C:/data/git/GoProjects/src/github.com/antchfx/xpath/query.go:236 +0x15f
github.com/antchfx/xpath.(*descendantQuery).Select(0xc0421ac540, 0xa40fa0, 0xc0420025c0, 0xc0420025c0, 0xc0421ac540)
        C:/data/git/GoProjects/src/github.com/antchfx/xpath/query.go:263 +0x3d
github.com/antchfx/xpath.(*NodeIterator).MoveNext(0xc0420025c0, 0xa492e0)
        C:/data/git/GoProjects/src/github.com/antchfx/xpath/xpath.go:85 +0x50
github.com/antchfx/xquery/xml.Find(0x0, 0x840722, 0xa, 0xc042071cf0, 0x4ddb82, 0xafaaa0)
        C:/data/git/GoProjects/src/github.com/antchfx/xquery/xml/query.go:54 +0x11a
GoAccept/functions.HandleScenario(0xc04200c480, 0x1b, 0x0)

```
So it is not giving me information about a malformed xml :-(

**Comment by zhengchun** [comment]
```go
s=`
<?xml version="1.0"?>
<Scenarios>
    <scenario>
        <one>1</one>
        <two>2</two>
        <three>3</tree>
    </scenario>
</Scenarios>
`
doc, err := xmlquery.Parse(strings.NewReader(s))
if err != nil {
    panic(err)
}
allScenarios := xmlquery.Find(doc, "//scenario")
fmt.Println(len(allScenarios))
```
`xmlquery.Parse()` will return error if an XML document is invalid, so you can check `err!=nil` to determine XML format is incorrect.

And about go's `Recover` feature you  can see here: [Defer, Panic, and Recover](https://blog.golang.org/defer-panic-and-recover)

**Comment by marcelloh** [comment]
the err after parse is perfect :-)
Thanks
