### ISSUE TITLE
Differente in usage

### ISSUE THREAD

**Issue by marcelloh** [antchfx/xquery#21]
More a question
To get an attribute in html:
```
href := htmlquery.SelectAttr(tag, "href")
```
to get it in xml:
```
debug := tag.SelectAttr("debug")
```
Why the difference?

**Comment by zhengchun** [comment]
`htmlquery` using Go's [html](https://godoc.org/golang.org/x/net/html) package to parse HTML document, its very fast and powerful. 

`xmlquery` using implementation own parser to parse XML document, so can easy to extend new method.

That's why `SelectAttr` function with different parameters.
