### ISSUE TITLE
predicates 不支持吗？

### ISSUE THREAD

**Issue by xywf221** [antchfx/xquery#25]
div[@class="page"]/a[last()]
这样不支持
div[@class="page"]/a[1]
这样也不支持
终于理解到不支持 predicates。

**Comment by zhengchun** [comment]
这种语法是支持的，建议你把报错的错误消息粘出来的以及测试的例子。https://github.com/antchfx/xpath/blob/master/xpath_test.go#L151

试试：`//div[@Class='page']/a[last()]`. 另外注意attribute健和值的大小写区分。

**Comment by xywf221** [comment]
。。。。问题解决了html中class的名称是单引号我写成双引号报错了。

**Comment by xywf221** [comment]
是支持的不知道咋天怎么回事莫名其妙的报错了，今天下班重新跑了下竟然正常了，可能是html源码的问题吧。比较用xpath趴取盗版小说网站

**Comment by xywf221** [comment]
另外FindOne这个函数能返回error不别直接panic 我这个xpath是动态的根据配置文件读取的,要做判断的

**Comment by zhengchun** [comment]
FindOne不会直接触发panic的错误，如果匹配不到，它是返回`nil`值。你要先判断是否为空，再进行下一步操作。比如：
```go
n:=htmlquery.FindOne(doc,"//a")
if n!=nil{
    fmt.Println(htmlquery.InnerText(n))
}
```

**Comment by xywf221** [comment]
https://github.com/antchfx/xquery/blob/d4ffaa903cebf0338c2ad8c5f10e2fd75213d0f3/html/query.go#L44
你这个直接panic了。

**Comment by zhengchun** [comment]
```go
exp, err := xpath.Compile(expr)
if err=nil{
    panic(err)
}
```
抱歉，没注意到。我以及为是类似于`FineOne(FindOne(doc,"a"),"span")`这种操作，FindOne这里前提条件是你的`expr`的表达式必须是正确的。所以，你必须先检查你输入的`expr`是正确的。你可以在`FindOne`操作前加判断。

**Comment by xywf221** [comment]
ok我去试试

**Comment by zhengchun** [comment]
或者你可以自己写一个`FindOne`的函数来代替htmlquery自带的`FindOne`. 因为它的先提条件就是先假设你输入的expr表达式是正确的。

```go
func FindOne(top *html.Node, expr string) (*html.Node,error) {
	var elem *html.Node
	exp, err := xpath.Compile(expr)
	if err != nil {
		return nil,err
	}
	t := exp.Select(htmlquery.CreateXPathNavigator(top))
	if t.MoveNext() {
		elem = (t.Current().(*htmlquery.NodeNavigator)).curr
	}
	return elem,nil
}
```
